@startuml
'https://plantuml.com/sequence-diagram

autonumber
StartMenu -> Account : login
StartMenu -> Account : register

Account -> User : getNickname
Account -> User : boolean askIfAdult

User -> LibraryMenu : showMenu(Kids)
User -> LibraryMenu : showMenu(All)

LibraryMenu -> Media : watch
LibraryMenu -> Media : watchLater
LibraryMenu -> Media : addToWatchLater




@enduml
